### ISSUE TITLE
View Superior Public Agencies

### ISSUE THREAD

**Issue by gabrielssilva** [GPP-MDS-2015-2/Aonde#19]
View a specific Superior Public Agency and the Public Agencies related to it

## Assignees
* @jpbusche
* @marcelohpf
* @EduardoMoreira 

## Tasks
* [x] Criar a rota e a pagina web
* [x] Criar os testes pro método que encontra os órgãos públicos e implementa-lo
* [x] Criar o métodos que adiciona o nó
* [x] Criar testes do método que adiciona o nó
* [x] Refatora método que criar nó e as ligações
* [x] Refatora código do JavaScript que criar o gráfico
* [x] Personaliza visual do gráfico
* [x] Criar testes de aceitação  
* [x] Pesquisar teste para módulo
* [x] Refatora os teste da controller do programa

**Comment by jpbusche** [comment]
Tasks: 
* [ ] Criar a rota e a pagina web
* [ ] Criar os testes pro método que encontra os órgãos públicos e implementa-lo
* [ ] Criar o métodos que adiciona o nó
* [ ] Criar testes do método que adiciona o nó
* [ ] Refatora método que criar nó e as ligações
* [ ] Refatora código do JavaScript que criar o gráfico
* [ ] Personaliza visual do gráfico
* [ ] Criar testes de aceitação
