### ISSUE TITLE
Add filter to Expense by Functions graph

### ISSUE THREAD

**Issue by gabrielssilva** [GPP-MDS-2015-2/Aonde#28]
Add filter to Expense by Functions graph

## Assignees

* @arthurTemporim 
* @arturbersan 

## Tasks
* [x] Pesquisar como fazer a filtragem
* [x] Pesquisar implementação dos testes com cucumber
* [x] Implementar filtro do gráfico
* [ ] Implementar testes com cucumber
* [x] Implementar método de ordenar funções
* [x] Implementar método de filtrar funções
* [x] Implementar teste de ordenar funções
* [x] Implementar teste de filtrar funções
