### ISSUE TITLE
Refactor BudgetController and PublicAgencyController

### ISSUE THREAD

**Issue by gabrielssilva** [GPP-MDS-2015-2/Aonde#33]
Refactor classes to reduce complexity and duplicated code, as stated on https://codeclimate.com/github/GPP-MDS-2015-2/Aonde/BudgetController and https://codeclimate.com/github/GPP-MDS-2015-2/Aonde/PublicAgencyController

## Assignees
* @marcelohpf 
* @arthurTemporim 
* @jpbusche 
* @arturbersan 

## Tasks
* [x] Separate  methods of API of controller budget
* [x] Separe tests of methods of API from controller budget test
* [x] Remove duplicate methods of public agency and companies and program
* [x] Create module of util methods
* [x] Test module of util methods
* [x] Add test to methods of public agency controller
* [ ] Complete the tests of controller function

**Comment by marcelohpf** [comment]
* [ ] Separe  methods of API of controller budget
* [ ] Separe tests of methods of API from controller budget test
* [ ] Remove duplicate methods
* [ ] Create module of util methods
* [ ] Test module of util methods
