### ISSUE TITLE
Add continuous deploy to production server

### ISSUE THREAD

**Issue by gabrielssilva** [GPP-MDS-2015-2/Aonde#36]
Add a continuous deploy tool to production server, linking to Travis CI

## Assignees
* @gabrielssilva

## Tasks
* [x] Generate and encrypt SSH deploy keys
* [x] Install and configure Capistrano, automating the deploy
* [x] Link Digital Ocean with Travis CI, via Capistrano
* [x] Add a swap disk to production server
* [ ] Autostart Openlink Virtuoso on server startup
