### ISSUE TITLE
Layout adjustments

### ISSUE THREAD

**Issue by eduardonunes2525** [GPP-MDS-2015-2/Aonde#43]
Finish layout adjustments

## Assignee
* @eduardonunes2525 
* @marcelohpf 

## Tasks
* [x] Figure out how to use a breadcumb
* [x] Create layout for removed items list (charts)
* [x] Add tooltips for every action button
* [x] Icon hover on items removal for charts
* [x] Icon hover on public agency list items
* [x] Loading screen to wait charts render
* [x] Prototype search element
* [x] Modify layout of Public Agencies
* [x] Modify layout of Function
* [x] Modify layout of Programs
* [x] Modify layout of Superior Agencies
* [x] Modify layout of Companies
* [x] Put the graphics inside the tabs
* [x] Put search field and filter
