### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by gabrielssilva** [GPP-MDS-2015-2/Aonde#44]
Increase test coverage (as in https://codeclimate.com/github/GPP-MDS-2015-2/Aonde/coverage), modularize Javascript graph scripts, and refactor BudgetController (an in https://codeclimate.com/github/GPP-MDS-2015-2/Aonde/BudgetController)

## Assignees
* @MatheusMiranda 
* @arturbersan 

## Tasks
* [x] Finish testing BudgetController
* [x] Finish testing FunctionController
* [x] Finish testing ApplicationHelper
* [x] Finish testing PublicAgencyHelper
* [x] Finish testing SearchController
* [x] Refactor BudgetController (B -> A)
* [x] Modularize Javascript (charts)
