### ISSUE TITLE
Improve Public Agency expenses chart

### ISSUE THREAD

**Issue by gabrielssilva** [GPP-MDS-2015-2/Aonde#45]
Change the chart used on the Public Agency

## Assignee
* @arthurTemporim 
* @jpbusche 

## Tasks
* [x] Research for the better chart for public agencies.
* [x] Implement chosen chart.
* [ ] Do backend needed methods.
* [ ] Test new methods.
* [ ] Improve chart.
