### ISSUE TITLE
Contact the administrator by e-mail

### ISSUE THREAD

**Issue by ebenezerandrade** [GPP-MDS-2015-2/Aonde#54]
Contact the administrator by e-mail

## Assignees
* @jpbusche
* @arthurTemporim

## Tasks
* [x] Research for action mailer
* [x] Implement mailer
* [x] Implement pleasing visual
* [x] Implement methods thats make conection with email
* [x] Test new methods
